# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTesthomepage():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testhomepage(self):
    self.driver.get("http://sayless.azurewebsites.net/login")
    self.driver.set_window_size(1552, 840)
    self.driver.find_element(By.ID, "emailInput").click()
    self.driver.find_element(By.ID, "emailInput").send_keys("shreyala@buffalo.edu")
    self.driver.find_element(By.ID, "passwordInput").send_keys("test1234")
    self.driver.find_element(By.CSS_SELECTOR, ".btn1").click()
    element = self.driver.find_element(By.ID, "autocomplete-3")
    assert element.is_enabled() is True
    assert self.driver.find_element(By.ID, "chat").text == "Start a New Chat"
    assert self.driver.find_element(By.ID, "chat").text == "Start a New Chat"
    self.driver.find_element(By.ID, "autocomplete-3").click()
    self.driver.find_element(By.ID, "autocomplete-3").send_keys("Shazmaan")
    self.driver.find_element(By.ID, "chat").click()
    self.driver.find_element(By.CSS_SELECTOR, ".message").click()
    assert self.driver.find_element(By.ID, "send").text == "Send"
    self.driver.find_element(By.CSS_SELECTOR, ".message").click()
    self.driver.find_element(By.CSS_SELECTOR, ".message").send_keys("test123")
    self.driver.find_element(By.ID, "send").click()
    assert self.driver.find_element(By.ID, "header").text == "shreyala"
  
