# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDeleteAcc():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_deleteAcc(self):
    # Test name: deleteAcc
    # Step # | name | target | value
    # 1 | open | /login | 
    self.driver.get("http://sayless.azurewebsites.net/login")
    # 2 | setWindowSize | 1536x824 | 
    self.driver.set_window_size(1536, 824)
    # 3 | click | id=emailInput | 
    self.driver.find_element(By.ID, "emailInput").click()
    # 4 | type | id=emailInput | jshrishty18@gmail.com
    self.driver.find_element(By.ID, "emailInput").send_keys("jshrishty18@gmail.com")
    # 5 | type | id=passwordInput | Password123
    self.driver.find_element(By.ID, "passwordInput").send_keys("Password123")
    # 6 | click | css=.submit |
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".submit")))
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".submit").click()
    # 7 | click | css=.fa-cog |
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".fa-cog")))
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".fa-cog").click()
    # 8 | click | linkText=Delete Account | 
    self.driver.find_element(By.LINK_TEXT, "Delete Account").click()
    # 9 | verifyElementPresent | css=.fa-home |
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".fa-home")))
    time.sleep(2)
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".fa-home")
    assert len(elements) > 0
    # 10 | verifyElementPresent | css=.fa-cog |
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".fa-cog")))
    time.sleep(2)
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".fa-cog")
    assert len(elements) > 0
    # 11 | verifyElementPresent | css=.fa-sign-out-alt |
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".fa-sign-out-alt")))
    time.sleep(2)
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".fa-sign-out-alt")
    assert len(elements) > 0
    # 12 | verifyElementPresent | id=yes | 
    elements = self.driver.find_elements(By.ID, "yes")
    assert len(elements) > 0
    # 13 | click | css=.fa-sign-out-alt |
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".fa-sign-out-alt")))
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".fa-sign-out-alt").click()
    # 14 | close |  | 
    self.driver.close()
  
