# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestResetPass():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  #Verify all elements are as they should be, correct text, editable if it should be, buttonclickable and bring to correct page
  def test_resetPass(self):
    self.driver.get("https://change-pass.netlify.app/")
    self.driver.set_window_size(1552, 840)
    assert self.driver.title == "SayLess - Reset_Password"
    assert self.driver.find_element(By.CSS_SELECTOR, "#reset > p:nth-child(1)").text == "Please Enter Your new Password"
    assert self.driver.find_element(By.CSS_SELECTOR, ".btn").text == "Reset"
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    element = self.driver.find_element(By.ID, "password")
    assert element.is_enabled() is True
    element = self.driver.find_element(By.ID, "password2")
    assert element.is_enabled() is True
    assert self.driver.find_element(By.CSS_SELECTOR, "#return > p").text == "Return To Login"
    self.driver.find_element(By.CSS_SELECTOR, "#return > p").click()
    assert self.driver.title == "SayLess Login"
    self.driver.close()
  
