# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLogin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_login(self):
    # Test name: login
    # Step # | name | target | value
    # 1 | open | /login | 
    self.driver.get("http://sayless.azurewebsites.net/login")
    # 2 | setWindowSize | 1552x840 | 
    self.driver.set_window_size(1552, 840)
    # 3 | verifyEditable | id=emailInput | 
    element = self.driver.find_element(By.ID, "emailInput")
    assert element.is_enabled() is True
    # 4 | verifyEditable | id=passwordInput | 
    element = self.driver.find_element(By.ID, "passwordInput")
    assert element.is_enabled() is True
    # 5 | assertElementPresent | linkText=Forgot password? | 
    elements = self.driver.find_elements(By.LINK_TEXT, "Forgot password?")
    assert len(elements) > 0
    # 6 | assertElementPresent | linkText=Sign up | 
    elements = self.driver.find_elements(By.LINK_TEXT, "Sign up")
    assert len(elements) > 0
    # 7 | assertElementPresent | css=.submit |
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".submit")))
    time.sleep(2)
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".submit")
    assert len(elements) > 0
    # 8 | click | id=emailInput | 
    self.driver.find_element(By.ID, "emailInput").click()
    # 9 | type | id=emailInput | jshrishty18@gmail.com
    self.driver.find_element(By.ID, "emailInput").send_keys("jshrishty18@gmail.com")
    # 10 | type | id=passwordInput | Password123
    self.driver.find_element(By.ID, "passwordInput").send_keys("Password123")
    # 11 | click | css=.submit |
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".submit")))
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".submit").click()
    # 12 | click | css=.fa-sign-out-alt |
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".fa-sign-out-alt")))
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".fa-sign-out-alt").click()
  
