# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLoginTest():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_loginTest(self):
    self.driver.get("https://loginsayless.netlify.app/")
    self.driver.set_window_size(1552, 840)
    assert self.driver.title == "SayLess Login"
    assert self.driver.find_element(By.CSS_SELECTOR, "h2").text == "Login"
    assert self.driver.find_element(By.CSS_SELECTOR, ".btn1").text == "Login"
    assert self.driver.find_element(By.LINK_TEXT, "Forgot password?").text == "Forgot password?"
    assert self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(7)").text == "New to SayLess? Sign up"
    self.driver.find_element(By.ID, "emailInput").click()
    self.driver.find_element(By.ID, "emailInput").send_keys("test@gmail.com")
    self.driver.find_element(By.ID, "passwordInput").click()
    self.driver.find_element(By.ID, "passwordInput").send_keys("hello123")
    self.driver.close()
  
