# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestBio():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_bio(self):
    # Test name: bio
    # Step # | name | target | value
    # 1 | open | /login | 
    self.driver.get("http://sayless.azurewebsites.net/login")
    # 2 | setWindowSize | 1552x840 | 
    self.driver.set_window_size(1552, 840)
    # 3 | click | id=emailInput | 
    self.driver.find_element(By.ID, "emailInput").click()
    # 4 | type | id=emailInput | jshrishty18@gmail.com
    self.driver.find_element(By.ID, "emailInput").send_keys("jshrishty18@gmail.com")
    # 5 | type | id=passwordInput | Password123
    self.driver.find_element(By.ID, "passwordInput").send_keys("Password123")
    # 6 | click | css=.submit |
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".submit")))
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".submit").click()
    # 7 | click | id=68e5c24d721256e216b4e804bb59de60da37d90a4e2dc98140bb5b7b77821479 |
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.ID, "openchat")))
    self.driver.find_element(By.ID, "68e5c24d721256e216b4e804bb59de60da37d90a4e2dc98140bb5b7b77821479").click()
    # 8 | selectFrame | index=0 | 
    self.driver.switch_to.frame(0)
    # 9 | click | css=button:nth-child(1) |
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(1)").click()
    # 10 | selectFrame | relative=parent |
    self.driver.switch_to.default_content()
    # 11 | click | css=.fa-sign-out-alt |
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".fa-sign-out-alt")))
    time.sleep(2)
    self.driver.find_element(By.CSS_SELECTOR, ".fa-sign-out-alt").click()
    # 12 | close |  |
    self.driver.close()
  
