# Generated by Selenium IDE
import pytest
import time
import json
import random
import string
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestChat():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_chat(self):
    # Test name: chat
    # Step # | name | target | value | comment
    # 1 | open | /login |  | 
    self.driver.get("http://sayless.azurewebsites.net/login")
    # 2 | setWindowSize | 1552x840 |  | 
    self.driver.set_window_size(1552, 840)
    # 3 | click | id=emailInput |  | 
    self.driver.find_element(By.ID, "emailInput").click()
    # 4 | type | id=emailInput | gptburc@gmail.com | 
    self.driver.find_element(By.ID, "emailInput").send_keys("gptburc@gmail.com")
    # 5 | type | id=passwordInput | password1234 | 
    self.driver.find_element(By.ID, "passwordInput").send_keys("password1234")
    # 6 | click | css=.submit |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".submit").click()
    # 7 | click | id=d7f054f94cf64bdc4f685942c4120a1766faeda3bcaa800399e4850c08ce77c4 |  | 
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.ID, "a67f49f0d38db92d851fd7915d8eb88df567d753c0a605fe50566c1a6915b191")))
    self.driver.find_element(By.ID, "a67f49f0d38db92d851fd7915d8eb88df567d753c0a605fe50566c1a6915b191").click()
    # 8 | selectFrame | index=0 |  | 
    self.driver.switch_to.frame(0)
    # 9 | verifyText | id=send | Send | 
    assert self.driver.find_element(By.ID, "send").text == "Send"
    # 10 | click | css=.emoji-wysiwyg-editor |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".emoji-wysiwyg-editor").click()
    # 11 | editContent | css=.emoji-wysiwyg-editor | Test Message | 
    element = self.driver.find_element(By.CSS_SELECTOR, ".emoji-wysiwyg-editor")
    random_string = ''.join(random.choices(string.ascii_uppercase + string.digits, k=8))
    self.driver.find_element(By.CSS_SELECTOR, ".emoji-wysiwyg-editor").send_keys(random_string)
    self.driver.find_element(By.ID, "send").click()
    #Resued LOGIN code becuase of how selenium treats socket connections
    self.driver.refresh()
    self.driver.get("http://sayless.azurewebsites.net/login")
    # 2 | setWindowSize | 1552x840 |  | 
    self.driver.set_window_size(1552, 840)
    # 3 | click | id=emailInput |  | 
    self.driver.find_element(By.ID, "emailInput").click()
    # 4 | type | id=emailInput | gptburc@gmail.com | 
    self.driver.find_element(By.ID, "emailInput").send_keys("gptburc@gmail.com")
    # 5 | type | id=passwordInput | password1234 | 
    self.driver.find_element(By.ID, "passwordInput").send_keys("password1234")
    # 6 | click | css=.submit |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".submit").click()
    # 7 | click | id=d7f054f94cf64bdc4f685942c4120a1766faeda3bcaa800399e4850c08ce77c4 |  | 
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.ID, "a67f49f0d38db92d851fd7915d8eb88df567d753c0a605fe50566c1a6915b191")))
    self.driver.find_element(By.ID, "a67f49f0d38db92d851fd7915d8eb88df567d753c0a605fe50566c1a6915b191").click()
    # 8 | selectFrame | index=0 |  | 
    self.driver.switch_to.frame(0)
    chat = self.driver.find_element_by_class_name("morediv").text
    assert random_string in chat, "message not sent into chat"
    # 12 | click | id=send |  | 
    self.driver.find_element(By.ID, "send").click()
    # 13 | verifyElementPresent | css=.morediv |  | 
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".morediv")
    assert len(elements) > 0
    # 14 | close |  |  | 
    self.driver.close()
  
