# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestHomepagetests():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_homepagetests(self):
    self.driver.get("http://sayless.azurewebsites.net/login")
    self.driver.set_window_size(1536, 824)
    self.driver.find_element(By.ID, "emailInput").click()
    self.driver.find_element(By.ID, "emailInput").send_keys("shreyala@buffalo.edu")
    self.driver.find_element(By.ID, "passwordInput").click()
    self.driver.find_element(By.ID, "passwordInput").send_keys("test1234")
    self.driver.find_element(By.CSS_SELECTOR, ".btn1").click()
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.ID, "autocomplete-3")))
    element = self.driver.find_element(By.ID, "autocomplete-3")
    assert element.is_enabled() is True
    assert self.driver.find_element(By.ID, "chat").text == "Chat"
    self.driver.find_element(By.ID, "autocomplete-3").click()
    self.driver.find_element(By.ID, "autocomplete-3").send_keys("Shazmaan")
    self.driver.find_element(By.ID, "chat").click()
    WebDriverWait(self.driver, 30000).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".message")))
    element = self.driver.find_element(By.CSS_SELECTOR, ".message")
    assert element.is_enabled() is True
    assert self.driver.find_element(By.ID, "send").text == "Send"
  
