# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestProfilepage():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_profilepage(self):
    self.driver.get("http://sayless.azurewebsites.net/login")
    self.driver.set_window_size(1552, 840)
    self.driver.find_element(By.ID, "emailInput").click()
    self.driver.find_element(By.ID, "emailInput").send_keys("shreyala@buffalo.edu")
    self.driver.find_element(By.ID, "passwordInput").send_keys("laathi2212")
    self.driver.find_element(By.CSS_SELECTOR, ".submit").click()
    self.driver.find_element(By.CSS_SELECTOR, ".fa-cog").click()
    self.driver.find_element(By.ID, "fn").click()
    self.driver.find_element(By.ID, "fn").send_keys("Shreya S")
    self.driver.find_element(By.ID, "ln").send_keys("Lakhkar L")
    self.driver.find_element(By.ID, "username").send_keys("shreya")
    self.driver.find_element(By.ID, "bio").send_keys("UB\'21")
    self.driver.find_element(By.ID, "new-pw").send_keys("paridhip1202")
    self.driver.find_element(By.ID, "update").click()
    self.driver.find_element(By.CSS_SELECTOR, ".fas").click()
    assert self.driver.find_element(By.ID, "bio_text").text == "UB\\\'21"
    self.driver.find_element(By.CSS_SELECTOR, ".fa-cog").click()
    self.driver.find_element(By.ID, "fn").click()
    self.driver.find_element(By.ID, "fn").send_keys("Shreya")
    self.driver.find_element(By.ID, "ln").send_keys("Lakhkar")
    self.driver.find_element(By.ID, "username").send_keys("shreyala")
    self.driver.find_element(By.ID, "bio").send_keys("UB 2021")
    self.driver.find_element(By.ID, "new-pw").send_keys("laathi2212")
    self.driver.find_element(By.ID, "update").click()
  
